### ISSUE TITLE
[Bug]: import autogen

### ISSUE THREAD

**Issue by MarkLo127** [ag2ai/ag2#167] opened 2024-12-07 22:02 UTC
I want import autogen

import autogen

but error message say:

ModuleNotFoundError: No module named 'openai.lib._parsing'

**Comment by qingyun-wu** [comment] 2024-12-07 22:40
@MarkLo127, could you make sure you have the latest openai version and latest autogen? 

```
pip uninstall openai pyautogen ag2
```
and then do
```
pip install pyautogen
```

**Comment by MarkLo127** [comment] 2024-12-08 01:12
The problem Wii be solved

tks

**Comment by qingyun-wu** [comment] 2024-12-08 05:11
@MarkLo127 problem is solved? If so, could you close the PR? Thanks!

**Comment by bassilkhilo** [comment] 2024-12-08 23:50
Hi @MarkLo127 

Please take a look at https://github.com/ag2ai/ag2/issues/169

This may solve the issue.

**Comment by Hk669** [comment] 2024-12-09 05:42
closing this issue, as @MarkLo127 mentioned the problem is solved. Thanks @qingyun-wu !

**Closed by Hk669** 2024-12-09 05:42 UTC
Labels: bug
